 # Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: ShowDirStage
  displayName: 'Show Dir Stage'
  jobs:
  - job: ShowArtifactDirJob
    displayName: 'ShowArtifDirJob'
    steps:       
    - script: |
       echo $(Build.ArtifactStagingDirectory) 
       #echo $(Build.ArtifactStagingDirectory) 
      displayName: 'Run ShowDirJob Script'     
  - job: ShowSourceDir
    steps:      
    - script: |
        echo $(Build.SourcesDirectory) 
        #echo $(Build.SourcesDirectory)
  - job: ShowBinariesDir
    steps:     
    - script: |
        echo $(Build.BinariesDirectory) 
        #echo $(Build.BinariesDirectory)    
  - job: ShowTestResultsDir
    steps:    
    - script: |
        echo $(Common.TestResultsDirectory) 
        #echo $(Common.TestResultsDirectory) 
      displayName: 'Run a multi-line script'


   
  
