# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: ShowDirStage
  jobs:
  - job: ShowArtifactDir
    steps:       
    - script: echo $(Build.ArtifactStagingDirectory)  
    #- script: echo $(Build.SourcesDirectory) 
  - job: ShowSourceDir
    steps:       
    #- script: echo $(Build.ArtifactStagingDirectory)  
    - script: echo $(Build.SourcesDirectory) 
  - job: ShowBinariesDir
    steps:     
    - script: echo $(Build.BinariesDirectory) 
    #- script: echo $(Common.TestResultsDirectory) 
  - job: ShowTestResultsDir
    steps:     
    #- script: echo $(Build.BinariesDirectory) 
    - script: echo $(Common.TestResultsDirectory) 

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
