 # Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Set variables once
variables:
  synopsysFile: 'C:\Users\niqfl\Downloads\devsecops\synopsys-detect-9.1.0.jar'
  #synopsysFile: 'synopsys-detect-9.1.0.jar'

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: ShowDirStage
  displayName: 'Show Dir Stage'
  jobs:
  - job: ShowDirJob
    displayName: 'ShowDirJob'
    steps:       
    - script: |
       echo $(Build.ArtifactStagingDirectory) 
       echo $(Build.SourcesDirectory) 
       echo $(Build.BinariesDirectory) 
       echo $(Common.TestResultsDirectory)        
      displayName: 'Show Dirs'     
  - job: ShowSourceDir
    steps:      
    - script: |
        echo $(Build.SourcesDirectory) 
        #echo $(Build.SourcesDirectory)
  - job: DoCopyFileJob
    steps:   
    - task: CopyFiles@2
      inputs:
        Contents: $(synopsysFile) 
        TargetFolder: ${AGENT_TOOLSDIRECTORY} 
        CleanTargetFolder: true
        OverWrite: true
        flattenFolders: true
        preserveTimestamp: true

  
